### ISSUE TITLE
SegNet model build fail

### ISSUE THREAD

**Issue by fatrybl** [janisgp/Sampling-free-Epistemic-Uncertainty#4]
Dear author,
Thank you very much for your research. I`ve read it with great interest!
I tried to implement classification with Bayessian SegNet model, but faced this problem while launching  SegNet-CamVid11-Bayesian.ipynb file. The packages are pretty fresh and the only difference from your requirements is Pillow package. My Pillow version is 7.0 But it seems like it isn`t gonna influence on that
![Screenshot from 2020-03-21 17-43-56](https://user-images.githubusercontent.com/22779281/77228958-e6880c00-6b9b-11ea-952b-5226c84b8a62.png)

I also tried to change parameter name to dropout_location = dropout_location. It didnt help.

**Comment by janisgp** [comment]
Hi @fatrybl 

Thanks for pointing this problem out. The parameter dropout_loc was a development artifact. I removed it in the latest commit. I further added a yaml file with the newer conda environment in which I just ran the notebook. Feel free to create a conda environment from it. 

Best,
Jansi

**Comment by janisgp** [comment]
Hi @fatrybl 

does this solve your problem?

Best,
Janis

**Comment by fatrybl** [comment]
Thanks for fast solution and reply! yeah, that problem has been solved, but another occurred.
![image](https://user-images.githubusercontent.com/22779281/77795831-417ba080-707f-11ea-957b-3e91cd866170.png)

![image](https://user-images.githubusercontent.com/22779281/77795801-358fde80-707f-11ea-848c-3aa410489701.png)

**Comment by janisgp** [comment]
Hey,

is the a folder called "y_3595640ea0b061d5422951ed3e1a7bf0" (or equivalently y_"some other hash") in the folder ".../Sampling-free-Epistemic-Uncertainty/Bayesian_SegNet/src/datasets/camvid" ? And if so, does it contain a file metadata.csv?

Best,
Janis

**Comment by janisgp** [comment]
Hey @fatrybl 

did you resolve the problem?

Best,
Janis

**Comment by janisgp** [comment]
@fatrybl 

can the issue be closed?

Best,
Janis

**Comment by fatrybl** [comment]
Frankly speaking, I did not chech yet, so you might close it, if you are sure that evrrything wotkd well 11.04.2020, 11:22, "janisgp" <notifications@github.com>:
@fatrybl
can the issue be closed?
Best,
Janis
