### ISSUE TITLE
Hello, could you please provide the exact version numbers of TensorFlow and Keras required for operation? I have tried many versions, but there are problems, thank you  

### ISSUE THREAD

**Issue by ellen19967** [janisgp/Sampling-free-Epistemic-Uncertainty#9]
Hello, could you please provide the exact version numbers of TensorFlow and Keras required for operation? I have tried many versions, but there are problems, thank you  !

**Comment by janisgp** [comment]
Hi,

sorry to hear that. What exactly are you trying to run and what issues are you encountering?

FYI: in case you are trying to run BayesianSegNet, there is "20200324_environment.yml" in the Bayesian_SegNet folder which was connected to another issue last year and should have the correct environment for running the BayesianSegNet notebook.

Best,
Janis

**Comment by ellen19967** [comment]
Thank you very much for your quick reply. I will try to configure it according to this file
